### ISSUE TITLE
[Feature] Reference styleguide values within SFC style blocks

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/enhance-styles#12]
I'd like to be able to reference styleguide values within style blocks within my single file components. My initial use case is to be able implement media query-fenced styles more programmatically — this would save a lot of find-and-replace operations when adjusting breakpoints and reduce the chances of mistyping a media query by hand.

A couple ideas come to mind:

# Optionally export `styleguide` as a JS object
Exporting the styleguide as a JS object would allow me to compose my styleguide out of smaller, reusable bits of Javascript. For example

```js
// app/lib/queries.mjs
export default {
  sm: '30em',
  md: '48em',
  lg: '64em',
  xl: '90em',
}

// styleguide.mjs
import queries from 'app/lib/queries'

export default {
  queries,
  …
}

// app/elements/my-component.mjs
import queries from 'app/lib/queries'

export default function MyComponent({ html }) {
  return html`
    <style>
      :host { color: palevioletred; }
      @media screen and (min-width: ${queries.lg}) {
        :host { color: rebeccapurple; }
      }
    </style>
    Hello world
  `
}
```

# Provide a built-in helper to use the styleguide's values
A built-in API for accessing the styleguide's values would eliminate some DIY work of the previous option; this may be more or less desirable for an end user.

Something to explore here is this would, for some properties, provide two different ways to refer to the same data. For example, colours defined in the styleguide's `colors` and `theme` fields could now be referenced with both JS _and_ via the CSS custom properties that are generated by Enhance Styles. This could be confusing…?

An example of how this might work:

```js
// app/elements/my-component.mjs
import { useStyleguide } from '@enhance/enhance-styles' // I know, this name is probably too Reacty 😅 

export default function MyComponent {
  const { queries } = useStyleguide()

  return html`
    <style>
      :host { color: palevioletred; }
      @media screen and (min-width: ${queries.lg}) {
        :host { color: rebeccapurple; }
      }
    </style>
    Hello world
  `
}
```

These are just the first two ideas that came to mind, happy to investigate alternatives!

**Comment by colepeters** [comment]
Something to keep in mind: Enhance Styles already generates CSS custom properties for colours; conceivably, it could do the same for other styleguide values like border radiuses, border widths, fonts, etc. Media queries are the one field that this pattern doesn't work with, because [CSS custom properties can't (currently) be used with media queries](https://www.stefanjudis.com/notes/can-we-have-custom-media-queries-please/). Hence this idea. However, this approach may invite more complexity than it solves.

For example, the aforementioned issue of the secondary approach exposing some styleguide values as both CSS custom properties _and_ as data via JS.

Additionally, what happens when some styles are rendered on the client instead of SSR? Does this open the door to a potential Bad Time?

**Comment by macdonst** [comment]
I ran into the same issue and would love to be able to access the query properties in my custom elements. Otherwise, we end up hard-coding these values in a lot of places. So I too would love to see a solution for this problem as well.

**Comment by colepeters** [comment]
Nice, I much prefer that naming to what I'd roughed out too 😂

**Comment by colepeters** [comment]
Similar: should we expose entries in `styleguide.fonts` as custom properties?

E.g.:

```json
{
  "fonts": {
    "sans": "Helvetica Neue, Helvetica, sans-serif"
  }
}
```

```css
.foo {
  font-family: var(--font-sans);
```

https://discord.com/channels/1012099764713705472/1059964929681141870/1139639690241245216

**Comment by colepeters** [comment]
Closing as we're now tracking this as a potential feature for Enhance Styles v7
