### ISSUE TITLE
Adopt logical properties

### ISSUE THREAD

**Issue by colepeters** [enhance-dev/enhance-styles#20]
**Reference: [CSS Logical Properties & Values](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties)**

Many of our utility classes are currently based on imperative properties, e.g. `margin-left`, `padding-top`, etc.

In order to offer better support for non-LTR writing modes, we should look into adopting logical properties. This will open Enhance Styles up to a wider range of developers and end users.

The following groupings of classes would be affected:

- margin
- padding
- border
- inset (T/R/B/L positioning)
- ~overflow~
- width
- height
- text-align

**Comment by kristoferjoseph** [comment]
This makes a lot of sense.
We definitely want to make this change sooner than later so as to be prepared for more users from other languages.

**Comment by colepeters** [comment]
Update: logical properties for `overflow` are currently only supported on Firefox. We'll have to skip that one until we have adoption across the board.
