### ISSUE TITLE
Grid alignment properties are missing from utility styles

### ISSUE THREAD

**Issue by ryanbethel** [enhance-dev/enhance-styles#23]
I might be missing something but I don't think there are utility classes generated for the following grid alignment properties:
- {align-items:start;}
- {align-items:end;}
- {align-self:start;}
- {align-self:end;}
- {justify-content:start;}
- {justify-content:end;}
Each of the properties does have a utility class that sets 'flex-start' or 'flex-end' instead. This makes it hard to add them without causing a breaking change or confusion. The class `items-start` corresponds to `.items-start {align-items:flex-start;}` which takes the most logical name for the `align-items:start` utility class. 

On the other hand the `align-content` property has utility classes for start and end while lacking `flex-start` and `flex-end`. 

The `justify-items` property and the `justify-self` properties do not have utility classes that set their value at all. I think these properties only affect Grid so they could probably be added without causing breaking changes.

**Comment by kristoferjoseph** [comment]
You are correct!
 This should be added with the logical properties approach.
Thanks for catching that.

**Comment by colepeters** [comment]
I'd previously mentioned that I thought we could drop the `flex-` values, but it turns out I was wrong. These are still used to take into account the times when `row-reverse` and `col-reverse` flex layouts are used.

Much more info: https://csslayout.news/whats-the-difference-between-the-alignment-values-of-start-flex-start-and-self-start/

So, this update will include the missing values, as well as options for values with and without the `flex-` prefix, since each can be used differently. 😵‍💫

**Comment by colepeters** [comment]
Further: as Ryan mentioned, `justify-items` and `justify-self` are ignored in flexbox layouts. However, these properties *can* be used inside block layouts and absolutely positioned layouts in addition to grid, which to me suggests the requisite classes shouldn't be named specifically for grid layouts (e.g. `grid-items-center`, `grid-self-center`, etc).

That said, `items-*` is already being used for `align-items` and `self-*` is already being used for `align-self`.

Options:

1. `justify-items-*` and `justify-self-*` (but this begs the question of 'why are `align-items`, `align-self`, and `justify-content` classes shortened, but these two `justify-*` classes aren't?
1. Rewrite the `align-*` classes to include `align-*` in the class name, as well as the `justify-content` classes, thus keeping all axial classes in the same naming pattern

@kristoferjoseph @ryanbethel Any preference? Or other ideas?

**Comment by kristoferjoseph** [comment]
This all makes sense. Thanks for digging in.
I think #2 makes the most sense seeing as the other align properties are already prefixed with text.
Can we move all axial classes into their own file with their own heading?
I'd love to be able to group all the alignment classes under one section in the cheat sheet.

**Comment by colepeters** [comment]
@kristoferjoseph Weird, we're on the same page. Thanks, it shall be done!

**Comment by ryanbethel** [comment]
#2 but I defer to you both as the real experts. Thanks for solving this puzzle 😆.

**Comment by colepeters** [comment]
@ryanbethel It's unanimous so I think you can consider yourself an expert on this one! 😄
