### ISSUE TITLE
more modular

### ISSUE THREAD

**Issue by kristoferjoseph** [enhance-dev/enhance-styles#36]
- [ ]  Split custom properties from class generation.
- [ ]  Only return css for present keys in the config

**Comment by colepeters** [comment]
## Custom properties wishlist

- `fonts` from `styleguide.json` as custom properties (e.g. `--font-sans`, `--font-serif`, `--font-mono`)

**Comment by colepeters** [comment]
Closing as we have this under consideration in the Enhance Styles v7 project
